# This workflow runs on a schedule and makes an http call to the specified URLs. It then heuristically checks the
# returned content for interesting changes and fails the workflow if they are detected.
#
#     https://wiki.dominionstrategy.com/index.php/Sentinel
name: Sentinel

on:
  schedule:
    # https://crontab.guru/#0_*/1_*_*_*
    #   “At minute 0 past every hour.” 
    - cron: '0 */1 * * *'
  # Manually trigger the workflow for testing
  workflow_dispatch:

jobs:
  # This job works as follows:
  #   1. Make an http call to the specified URL and store the response in a file
  #   2. Check the response for interesting changes
  #       - Check if a course's availability has changed
  #       - Check if a course's date has changed
  #       - Check if new courses have been added
  #       - Check if existing courses have been removed
  #   3. Fail the workflow if any of the checks fail
  #
  # The part of the response we're inspecting can be inspected under `response_excerpt.md` in the project root.
  sentinel:
    runs-on: ubuntu-latest
    steps:
      - name: Make call
        run: curl --silent --show-error --location https://baedershop.l.de/de/kleinkinderschwimmen > /tmp/response
      - name: Debug output
        run: cat /tmp/response
      # A and B should fail if the availability or date of a course changes
      - name: Check availability and date of course A
        run: grep --quiet --perl-regexp 'Montag, 06\.Januar 16:15 Uhr.*?\(ausgebucht\)' /tmp/response
      - name: Check availability and date of course B
        run: grep --quiet --perl-regexp 'Montag, 06\.Januar 16:45 Uhr.*?\(ausgebucht\)' /tmp/response
      # C should fail if additional courses are added (or the existing ones are removed)
      - name: Check number of courses
        run: |
          NUMBER_OF_COURSES=$(grep --only-matching '\.product-schedules-date' /tmp/response | wc --lines)
          if [ "$NUMBER_OF_COURSES" -ne 2 ]; then
            echo "Number of courses has changed, expected 2, got $NUMBER_OF_COURSES"
            exit 1
          fi
      # Only to test the failure, normally commented out
      #- name: Test failure of availability and date check
      #  run: grep --quiet --perl-regexp 'THIS IS NOT CONTAINED IN THE RESPONSE auqiehtaipehpaihwerahiaww' /tmp/response
      - name: Test failure of number of courses check
        run: |
          NUMBER_OF_COURSES=$(grep --only-matching '\.product-schedules-date' /tmp/response | wc --lines)
          if [ "$NUMBER_OF_COURSES" -ne 1 ]; then
            echo "Number of courses has changed, expected 2, got $NUMBER_OF_COURSES"
            exit 1
          fi
