# This workflow runs on a schedule and makes an http call to the specified URLs. It then heuristically checks the
# returned content for interesting changes and fails the workflow if they are detected.
#
#     https://wiki.dominionstrategy.com/index.php/Sentinel
name: Sentinel

on:
  # Disabled until needed again
  # schedule:
  #   # https://crontab.guru/#0_*/1_*_*_*
  #   #   “At minute 0 past every hour.” 
  #   - cron: '0 */1 * * *'
  # Manually trigger the workflow for testing
  workflow_dispatch:

jobs:
  # This job works as follows:
  #   1. Make an http call to the specified URL and store the response in a file
  #   2. Check the response for interesting changes
  #       - Check if new courses have been added
  #   3. Fail the workflow if any of the checks fail
  #
  # The part of the response we're inspecting can be inspected under `response_excerpt.md` in the project root.
  sentinel:
    runs-on: ubuntu-latest
    steps:
      - name: Make call
        run: curl --silent --show-error --location https://baedershop.l.de/de/kleinkinderschwimmen > /tmp/response
      - name: Debug output
        run: cat /tmp/response
      # This should fail if a 'schedulesproducts' class is added (which it was in v1 with the unavailable courses)
      - name: Check for new courses
        run: |
          NUMBER_OF_SCHEDULED_PRODUCTS=$(grep --only-matching 'class=scheduledproducts' /tmp/response | wc --lines)
          if [ "$NUMBER_OF_SCHEDULED_PRODUCTS" -ne 0 ]; then
            echo "Number of scheduled products has changed, expected 0, got $NUMBER_OF_SCHEDULED_PRODUCTS"
            exit 1
          fi
      # This should should fail if additional courses are added (or the existing ones are removed)
      - name: Check number of courses
        run: |
          NUMBER_OF_COURSES=$(grep --only-matching '\.product-schedules-date' /tmp/response | wc --lines)
          if [ "$NUMBER_OF_COURSES" -ne 0 ]; then
            echo "Number of courses has changed, expected 0, got $NUMBER_OF_COURSES"
            exit 1
          fi
